---

#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  # Disable ES6 since we are not transpliling and need to support IE
  es6: false
  jest: true

###############
# Global Vars #
###############
globals:
  $: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  # need to support IE, so use EcmaScript 5 parser
  # https://caniuse.com/?search=es5
  # https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options
  ecmaVersion: 5
  sourceType: module

###########
# Plugins #
###########
plugins:
  - '@typescript-eslint'

#########
# Rules #
#########
extends: "eslint:recommended"
rules: {}

##############################
# Overrides for JSON parsing #
##############################
overrides:

# JSON files
- files:
  - "*.json"
  extends:
  - plugin:jsonc/recommended-with-json
  parser: jsonc-eslint-parser
  parserOptions:
    ecmaVersion: 2018
    jsonSyntax: JSON

# JSONC files
- files:
  - "*.jsonc"
  extends:
  - plugin:jsonc/recommended-with-jsonc
  parser: jsonc-eslint-parser
  parserOptions:
    ecmaVersion: 2018
    jsonSyntax: JSONC

# JSON5 files
- files:
  - "*.json5"
  extends:
  - plugin:jsonc/recommended-with-json5
  parser: jsonc-eslint-parser
  parserOptions:
    ecmaVersion: 2018
    jsonSyntax: JSON5
